<a href="https://colab.research.google.com/github/eyaGONGI/Codersquare/blob/main/Titanic_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import pandas as pd
df_Titanic= pd.read_csv('/content/titanic.csv')
df_Titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

the percentage of people who survived

In [82]:
df_Titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [84]:
per_survived = len(df_Titanic[df_Titanic['Survived']==1])/len(df_Titanic)
per_survived

0.3838383838383838

Survived of each sex

In [86]:
survived_sex = df_Titanic.groupby(by=["Sex","Survived"]).sum()
survived_sex

<ipython-input-86-55e8aed82299>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  survived_sex = df_Titanic.groupby(by=["Sex","Survived"]).sum()

                 PassengerId  Pclass       Age  SibSp  Parch        Fare
Sex    Survived
female 0               35223     231   1603.00     98     84   1864.9752
       1              100120     447   5683.00    120    120  12101.6876
male   0              210189    1159  11382.50    206     97  10277.7447
       1               51854     220   2536.67     42     39   4449.5418

In [105]:
survived=len(df_Titanic[df_Titanic["Survived"]==1])
survived

342

In [106]:
unsurvived=len(df_Titanic[df_Titanic["Survived"]==0])
unsurvived

549

In [59]:
passengers_less_10=df_Titanic['Fare'] < 10
passengers_less_10

0       True
1      False
2       True
3      False
4       True
       ...
886    False
887    False
888    False
889    False
890     True
Name: Fare, Length: 891, dtype: bool

In [60]:
df_Titanic['Fare'].value_counts()

8.0500     43
13.0000    42
7.8958     38
7.7500     34
26.0000    31
           ..
35.0000     1
28.5000     1
6.2375      1
14.0000     1
10.5167     1
Name: Fare, Length: 248, dtype: int64

In [61]:
df_Titanic[passengers_less_10].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S

In [62]:
survived_less_10= df_Titanic[passengers_less_10]['Survived'].value_counts(normalize = True)
survived_less_10

0    0.800595
1    0.199405
Name: Survived, dtype: float64

what is the average age of those who didn't survive?

In [63]:
df_Titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [91]:
group_age = df_Titanic.groupby(by=["Survived"]).mean()
group_age

<ipython-input-91-88fded5337bf>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  group_age = df_Titanic.groupby(by=["Survived"]).mean()

          PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [92]:
group_age["Age"][0]

30.62617924528302

what is the average age of those who did survive?

In [93]:
group_age["Age"][1]

28.343689655172415

the average age of those who did and didn't survive grouped by Sex?

In [101]:
survived_sex_age=df_Titanic.groupby(by=["Survived","Sex"]).sum()

<ipython-input-101-221ec6652c32>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  survived_sex_age=df_Titanic.groupby(by=["Survived","Sex"]).sum()

In [102]:
survived_sex_age

                 PassengerId  Pclass       Age  SibSp  Parch        Fare
Survived Sex
0        female        35223     231   1603.00     98     84   1864.9752
         male         210189    1159  11382.50    206     97  10277.7447
1        female       100120     447   5683.00    120    120  12101.6876
         male          51854     220   2536.67     42     39   4449.5418

In [108]:
print('the average age of unsurvived female',1603/len(df_Titanic))
print('the average age of unsurvived male',11382.5/len(df_Titanic))
print('the average age of survived female',5683/len(df_Titanic))
print('the average age of survived male',2536.67/len(df_Titanic))

the average age of unsurvived female 1.7991021324354657
the average age of unsurvived male 12.774971941638608
the average age of survived female 6.378226711560045
the average age of survived male 2.8469921436588104